[package]
name = "lispfmt"
description = "A universal formatter for the Lisp family of programming languages."
version = "0.1.0"
authors = ["Miika Kurvinen <myuwi@proton.me>"]
license = "ISC"
edition = "2024"

[dependencies]
ariadne = "0.6.0"
chumsky = "0.11.2"
pretty = "0.12.5"
